{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  labels:
    {{- include "mongo-express.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "{{ .Release.Name }}.{{ .Release.Namespace }}.{{ .Chart.AppVersion }}.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "mongo-express.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
